### ISSUE TITLE
deoplete 'Error calling function' when editing Phoenix controller file

### ISSUE THREAD

**Issue by Quintasan** [awetzel/elixir.nvim#10]
Today I tried to work on my Phoenix side project but deoplete wouldn't stop whining about that. I'm running neovim from Ubuntu PPA with neovim python extension installed from pip.
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/quintasan/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_results
[deoplete]     charpos = source.get_complete_position(ctx)
[deoplete]   File "/home/quintasan/.config/nvim/plugins/elixir.nvim/rplugin/python3/deoplete/sources/elixir.py", line 20, in get_complete_position
[deoplete]     return self.vim.call('ElixirComplete', "1", "")
[deoplete]   File "/home/quintasan/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/home/quintasan/.local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/home/quintasan/.local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Error calling function.'
[deoplete] Could not get completions from: elixir.  Use :messages for error details.
```

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 1ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xclip

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - INFO: Ruby: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
  - INFO: Host: /home/quintasan/.rvm/gems/ruby-2.4.0@global/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.3.1
```

**Comment by jcelliott** [comment]
I'm seeing the same error, but it happens in any Elixir file, not just a Phoenix controller.

**Comment by Quintasan** [comment]
If this helps then I installed Elixir and Erlang using `asdf`

**Comment by pggalaviz** [comment]
Having the exact same issue, on MacOS & elixir 1.4.5, on any elixir file when entering insert mode.
Any clue what is causing this?

**Comment by dmix** [comment]
I got it to work after having the same issue on MacOS. The solution is to navigate to the elixir.nvim plugin directory and manually run ./install.sh then open nvim again and run: `:UpdateRemotePlugins`. 

This should register the `nvim_rplugin-0.0.1.ez` plugin that gets built with the install script.

This seems to be missing from the install instructions.
